# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

default_platform(:ios)

platform :ios do
  desc "Build and install to device"
  lane :device do
    # Build for device
    build_app(
      workspace: "kiloworld.xcworkspace",
      scheme: "kiloworld",
      configuration: "Debug",
      destination: "id=00008140-000A292A0CE0801C",
      buildlog_path: "./fastlane/logs"
    )
  end

  desc "Build for device"
  lane :build do
    build_app(
      workspace: "kiloworld.xcworkspace", 
      scheme: "kiloworld",
      configuration: "Debug",
      destination: "generic/platform=iOS",
      skip_package_ipa: true,
      skip_archive: true,
      buildlog_path: "./fastlane/logs"
    )
  end
end